DEFAULTS = {
    "network_mode": "ap",
    "ap_ssid": "wage-net",
    "ap_password": "",
    "ap_ip": "192.168.50.1",
    "ap_pmf": "0",
    "ap_band": "bg",
    "ap_channel": "6",
    "ap_dhcp_start": "192.168.50.50",
    "ap_dhcp_end": "192.168.50.150",
    "client_ssid": "",
    "client_password": "",
    "client_dhcp_enabled": "true",
    "last_network_apply_status": "never",
    "last_network_apply_at": "",
    # Pi Hardware
    "pi_led_count": "8",
    "pi_led_brightness": "32",
    "pi_led_strip_count": "4",
    "pi_led_strip_pixels": "40",
    "pi_led_strip_sizes": "80,80,82,82",
    "pi_oled_rotation": "0",
    "power_save_after_minutes": "1",
}
