[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  bogde/HX711 @ ^0.7.5
  adafruit/Adafruit GFX Library @ ^1.11.9
  adafruit/Adafruit SH110X @ ^2.1.10
  fastled/FastLED

; OTA-Upload per WLAN (PlatformIO -> ESP direkt):
; pio run -e esp32dev-ota -t upload
; Voraussetzung: ESP läuft mit ArduinoOTA, PC im selben Netz (192.168.50.x)
[env:esp32dev-ota]
extends = env:esp32dev
upload_protocol = espota
upload_port = 192.168.50.100   ; statische IP des ESP
upload_flags = --auth=wagefirmware
